version: '3.6'
services:
  gitlab:
    image: registry.okcs.com/containers/gitlab/gitlab-ce:17.7.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.brizo.me'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.brizo.me'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        letsencrypt['enable'] = false
        # if you need ldap configuration uncomment this 
        # gitlab_rails['ldap_enabled'] = true
        # gitlab_rails['ldap_servers'] = {
        #   'main' => {
        #     'label' => 'LDAP',
        #     'host' =>  'ipa.brizoproj.test',
        #     'port' => 389,
        #     'uid' => 'uid',
        #     'bind_dn' => 'uid=admin,cn=users,cn=accounts,dc=brizoproj,dc=test',
        #     'password' => 'brizo123',
        #     'encryption' => 'plain',
        #     'verify_certificates' => false,
        #     'timeout' => 10,
        #     'active_directory' => false,
        #     'base' => 'cn=users,cn=accounts,dc=brizoproj,dc=test',
        #     'lowercase_usernames' => 'false',
        #     'retry_empty_result_with_codes' => [80],
        #     'allow_username_or_email_login' => false,
        #     'block_auto_created_users' => false
        #   }
        # }
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
