version: '3.8'

services:
  freeipa-server:
    image: freeipa/freeipa-server:rocky-9-4.12.2
    container_name: freeipa-server-container
    hostname: ipa.brizo.me
    environment:
      - IPA_SERVER_IP=10.192.127.237
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "10.192.127.237:53:53"
      - "10.192.127.237:53:53/udp"
    volumes:
      - ipa-data:/data
    stdin_open: true
    tty: true
    command: ipa-server-install -r BRIZO.ME --setup-dns --no-ntp --ip-address=10.192.127.237
      #cap_add:
      #  - NET_ADMIN
    dns:
      - 127.0.0.1
    extra_hosts:
      - "ipa.brizo.me:10.192.127.237"
      - "ipa:10.192.127.237"
    networks:
      freeipa-network:
        ipv4_address: 172.18.0.10


volumes:
  ipa-data:


networks:
  freeipa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
