{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "flask-app.fullname" . }}-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.httpPort }}
{{- end }}
