{{- if .Values.middleware.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.middleware.auth.secret }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
data:
  users: {{ .Values.auth.users }}
{{- end }}
