global:
  enable: true
  tlsDisable: false
  namespace: "vault-server"

injector:
  enabled: true

server:
  enable: true
  extraEnvironmentVars:
     VAULT_CACERT: /vault/userconfig/vault-tls/vault.ca
     VAULT_TLSCERT: /vault/userconfig/vault-tls/vault.crt
     VAULT_TLSKEY: /vault/userconfig/vault-tls/vault.key
  volumes:
    - name: userconfig-vault-tls
      secret:
        defaultMode: 420
        secretName: vault-tls
  volumeMounts:
     - mountPath: /vault/userconfig/vault-tls
       name: userconfig-vault-tls
       readOnly: true

  dataStorage:
    storageClass: k8s-cephfs

  standalone:
    enabled: true
    config: |-
      ui = true

      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-tls/vault.ca"
      }
      storage "file" {
        path = "/vault/data"
      }


ui:
  enabled: true
  serviceType: "NodePort"
  serviceNodePort: 30820
